import dotenv from "dotenv";
dotenv.config();

const {
    PORT,
    DATABASE_NAME,
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_DIALECT,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    NODE_ENV,    
    BCRYPT_SALT,
    ESEWA_SECRET_KEY,
    ESEWA_MERCHENT_ID,
    ESEWA_PAYMENT_INITIATE_URL,    
    ESEWA_PAYMENT_STATUS_CHECK_URL,
    PAYMENT_SUCCESS_URL,
    PAYMENT_FAILURE_URL,
    ESEWA_FAILURE_URL,
    KHALTI_SECRET_KEY,
    KHALTI_PAYMENT_INITIATE_URL,
    KHALTI_PAYMENT_STATUS_CHECK_URL,
    FRONTEND_URL
}= process.env

export const config = {
    PORT,
    DB_NAME: DATABASE_NAME,
    DB_USER: DATABASE_USER,
    DB_PASSWORD: DATABASE_PASSWORD,
    DB_HOST: DATABASE_HOST,
    DB_PORT: DATABASE_PORT,
    DB_DIALECT: DATABASE_DIALECT,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    NODE_ENV,
    BCRYPT_SALT,
    ESEWA_SECRET_KEY,
    ESEWA_MERCHENT_ID,
    ESEWA_PAYMENT_INITIATE_URL,
    ESEWA_PAYMENT_STATUS_CHECK_URL,
    PAYMENT_SUCCESS_URL,
    PAYMENT_FAILURE_URL,
    ESEWA_FAILURE_URL,
    KHALTI_SECRET_KEY,
    KHALTI_PAYMENT_INITIATE_URL,
    KHALTI_PAYMENT_STATUS_CHECK_URL,
    FRONTEND_URL
};